name: Setting up public registry
description: Add Registry to Julia Environment
inputs:
  token:
    description: Pesonal access token (PAT) for access to private registry.
    required: false
  registry_path:
    description: User or organization with registry path.
    required: true
    
runs:
  using: "composite"
  steps:
    - run: |
        julia -e '
          using Pkg
          Pkg.instantiate()
          Pkg.Registry.add(RegistrySpec(url = "https://${{ inputs.token }}@github.com/${{ inputs.registry_path}}.git"))
          Pkg.Registry.update()
          '
      shell: bash
branding:
  icon: "package"
  color: "green"
