name: Setting up public registry
description: Add Registry to Julia Environment
runs:
  using: "composite"
  steps:
    - run: |
        julia -e '
          using Pkg
          Pkg.instantiate()
          Pkg.Registry.add(RegistrySpec(url = "https://github.com/MyExampleOrg/MyPublicRegistry.git"))
          Pkg.Registry.update()
          '
      shell: bash
branding:
  icon: "package"
  color: "purple"
