name: 'Register a package'
on:
  workflow_call:
    inputs:
      registrator_name:
        description: 'Registrator name for git config'
        required: false
        default: 'github-actions[bot]'
        type: string
      registrator_email:
        description: 'Registrator email for git config'
        required: false
        default: 'github-actions[bot]@users.noreply.github.com'
        type: string
jobs:
  registry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
      
      - name: Configure Git
        run: |
          sudo apt-get update -qq && sudo apt-get install -y -qq git
          git config --global user.email ${{ inputs.registrator_email }}
          git config --global user.name ${{ inputs.registrator_name }}
  
      - name: Registration of julia package
        env:
          JULIA_REGISTRY: "https://${{ secrets.REGISTRATOR_TOKEN_2 }}@github.com/MyExampleOrg/ExampleRegistry.jl"
          REPOSITORY_PATH: "${{ github.repository }}"#"${{ inputs.repository }}"
        run: |
          julia -e '
          using Pkg
          Pkg.update()
          
          Pkg.Registry.add(RegistrySpec(url = ENV["JULIA_REGISTRY"]))
          Pkg.develop(url = "https://github.com/" * ENV["REPOSITORY_PATH"] * ".git")
          
          Pkg.add("LocalRegistry")
          using LocalRegistry
  
          name = first(split(basename("$(ENV["REPOSITORY_PATH"])"), "."))
  
          LocalRegistry.register(
            name,
            registry = ENV["JULIA_REGISTRY"],
            commit = true, push = true,
            ignore_reregistration = true,
          )
          '
          
